
server:
  port: 8089
#-----------------------------------数据库配置----------------------------------------
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatisplus?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root


logging:
  level:
    root: info
    com.cesar.core: trace
#  pattern:
#    console: '%p%m%n'

mybatis-plus:
  type-aliases-package: com.cesar.core.*.entity

jacob:
  cmsServerUrl: http://172.20.55.26:8089/jod/upload
  localStorePath: D:\ztemp\file\docserver\