
server:
  port: 8080
#-----------------------------------数据库配置----------------------------------------
spring:
  profiles:
    active: sqlserver

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sys?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
